"""initial schema

Revision ID: a903c6999912
Revises: 
Create Date: 2026-07-19 14:10:47.536590
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'a903c6999912'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Extensions relied on by column types / indexes below: citext (case-
    # insensitive emails/domains), pg_trgm (fuzzy-match GIN indexes), postgis
    # (Geography columns), vector (pgvector embedding column + ivfflat index).
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['business_categories.id'], name=op.f('fk_business_categories_parent_id_business_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_business_categories_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_business_categories_slug'))
    )
    op.create_table('companies',
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('legal_name', sa.String(length=500), nullable=True),
    sa.Column('slug', sa.String(length=550), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='discovered', nullable=False),
    sa.Column('year_established', sa.SmallInteger(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=2048), nullable=True),
    sa.Column('employee_count_range', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('merged_into_company_id', sa.UUID(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_crawled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_enriched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merged_into_company_id'], ['companies.id'], name=op.f('fk_companies_merged_into_company_id_companies'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies')),
    sa.UniqueConstraint('slug', name=op.f('uq_companies_slug'))
    )
    op.create_index('ix_companies_last_crawled_at', 'companies', ['last_crawled_at'], unique=False)
    op.create_index('ix_companies_name_trgm', 'companies', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index('ix_companies_status', 'companies', ['status'], unique=False)
    op.create_table('developers',
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('slug', sa.String(length=550), nullable=False),
    sa.Column('website_url', sa.String(length=2048), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=2048), nullable=True),
    sa.Column('headquarters_city', sa.String(length=150), nullable=True),
    sa.Column('headquarters_state', sa.String(length=150), nullable=True),
    sa.Column('established_year', sa.SmallInteger(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_developers')),
    sa.UniqueConstraint('slug', name=op.f('uq_developers_slug'))
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('users',
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_superuser', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('addresses',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('address_type', sa.String(length=20), server_default='corporate_office', nullable=False),
    sa.Column('line1', sa.String(length=500), nullable=True),
    sa.Column('line2', sa.String(length=500), nullable=True),
    sa.Column('locality', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=150), nullable=True),
    sa.Column('state', sa.String(length=150), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), server_default='India', nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_addresses_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_addresses'))
    )
    op.create_index('ix_addresses_city', 'addresses', ['city'], unique=False)
    op.create_index('ix_addresses_company_id', 'addresses', ['company_id'], unique=False)
    op.create_index('ix_addresses_geom', 'addresses', ['geom'], unique=False, postgresql_using='gist')
    op.create_table('ai_summaries',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('summary_markdown', sa.Text(), nullable=True),
    sa.Column('structured_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_ai_summaries_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_summaries'))
    )
    op.create_index('ix_ai_summaries_embedding', 'ai_summaries', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('uq_ai_summaries_company_current', 'ai_summaries', ['company_id'], unique=True, postgresql_where=sa.text('is_current'))
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('ix_audit_logs_user_created', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('company_categories',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['business_categories.id'], name=op.f('fk_company_categories_category_id_business_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_company_categories_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'category_id', name=op.f('pk_company_categories'))
    )
    op.create_table('company_developer_partnerships',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('developer_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=30), server_default='channel_partner', nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_company_developer_partnerships_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], name=op.f('fk_company_developer_partnerships_developer_id_developers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_developer_partnerships')),
    sa.UniqueConstraint('company_id', 'developer_id', 'relationship_type', name='uq_company_developer_relationship')
    )
    op.create_table('company_specializations',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('specialization', sa.String(length=30), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('source', sa.String(length=20), server_default='ai_extraction', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_company_specializations_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_specializations')),
    sa.UniqueConstraint('company_id', 'specialization', name='uq_company_specialization')
    )
    op.create_index(op.f('ix_company_specializations_specialization'), 'company_specializations', ['specialization'], unique=False)
    op.create_table('contacts',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('designation', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=150), nullable=True),
    sa.Column('linkedin_url', sa.String(length=2048), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_contacts_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts'))
    )
    op.create_index('ix_contacts_company_id', 'contacts', ['company_id'], unique=False)
    op.create_table('google_maps_listings',
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('place_id', sa.String(length=255), nullable=False),
    sa.Column('listing_name', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=150), nullable=True),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('formatted_address', sa.String(length=1000), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('website_url', sa.String(length=2048), nullable=True),
    sa.Column('opening_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('price_level', sa.SmallInteger(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_google_maps_listings_company_id_companies'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_google_maps_listings')),
    sa.UniqueConstraint('place_id', name=op.f('uq_google_maps_listings_place_id'))
    )
    op.create_index('ix_google_maps_listings_company_id', 'google_maps_listings', ['company_id'], unique=False)
    op.create_index('ix_google_maps_listings_geom', 'google_maps_listings', ['geom'], unique=False, postgresql_using='gist')
    op.create_table('lead_scores',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('website_completeness_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('digital_presence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('business_maturity_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('service_breadth_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('geographic_coverage_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('review_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('scoring_version', sa.String(length=50), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_lead_scores_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead_scores'))
    )
    op.create_index('ix_lead_scores_company_computed', 'lead_scores', ['company_id', 'computed_at'], unique=False)
    op.create_table('projects',
    sa.Column('developer_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('slug', sa.String(length=550), nullable=False),
    sa.Column('project_type', sa.String(length=20), server_default='residential', nullable=False),
    sa.Column('status', sa.String(length=30), server_default='under_construction', nullable=False),
    sa.Column('city', sa.String(length=150), nullable=True),
    sa.Column('state', sa.String(length=150), nullable=True),
    sa.Column('locality', sa.String(length=255), nullable=True),
    sa.Column('pincode', sa.String(length=20), nullable=True),
    sa.Column('rera_number', sa.String(length=100), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], name=op.f('fk_projects_developer_id_developers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index('ix_projects_city', 'projects', ['city'], unique=False)
    op.create_index('ix_projects_developer_id', 'projects', ['developer_id'], unique=False)
    op.create_index('ix_projects_geom', 'projects', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('ix_projects_rera_number', 'projects', ['rera_number'], unique=False)
    op.create_table('rera_details',
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=False),
    sa.Column('registrant_name', sa.String(length=500), nullable=False),
    sa.Column('registrant_type', sa.String(length=20), server_default='agent', nullable=False),
    sa.Column('registered_address', sa.Text(), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('matched_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_rera_details_company_id_companies'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rera_details')),
    sa.UniqueConstraint('registration_number', name=op.f('uq_rera_details_registration_number'))
    )
    op.create_index('ix_rera_details_registrant_name_trgm', 'rera_details', ['registrant_name'], unique=False, postgresql_using='gin', postgresql_ops={'registrant_name': 'gin_trgm_ops'})
    op.create_table('scrape_jobs',
    sa.Column('job_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('parent_job_id', sa.UUID(), nullable=True),
    sa.Column('queue_name', sa.String(length=50), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default='3', nullable=False),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_scrape_jobs_company_id_companies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_job_id'], ['scrape_jobs.id'], name=op.f('fk_scrape_jobs_parent_job_id_scrape_jobs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scrape_jobs'))
    )
    op.create_index('ix_scrape_jobs_company_id', 'scrape_jobs', ['company_id'], unique=False)
    op.create_index('ix_scrape_jobs_status_type', 'scrape_jobs', ['status', 'job_type'], unique=False)
    op.create_table('service_areas',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('area_type', sa.String(length=20), server_default='city', nullable=False),
    sa.Column('city', sa.String(length=150), nullable=True),
    sa.Column('state', sa.String(length=150), nullable=True),
    sa.Column('locality', sa.String(length=255), nullable=True),
    sa.Column('pincode', sa.String(length=20), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geography(srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('source', sa.String(length=20), server_default='ai_extraction', nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_service_areas_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_areas'))
    )
    op.create_index('ix_service_areas_city', 'service_areas', ['city'], unique=False)
    op.create_index('ix_service_areas_company_id', 'service_areas', ['company_id'], unique=False)
    op.create_index('ix_service_areas_geom', 'service_areas', ['geom'], unique=False, postgresql_using='gist')
    op.create_table('social_profiles',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('handle', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('follower_count', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_social_profiles_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_social_profiles')),
    sa.UniqueConstraint('company_id', 'url', name='uq_social_profiles_company_url')
    )
    op.create_index(op.f('ix_social_profiles_platform'), 'social_profiles', ['platform'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('websites',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('domain', postgresql.CITEXT(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='unknown', nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_websites_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_websites')),
    sa.UniqueConstraint('company_id', 'url', name='uq_websites_company_url')
    )
    op.create_index('ix_websites_domain', 'websites', ['domain'], unique=False)
    op.create_table('change_history',
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('change_source', sa.String(length=20), server_default='system', nullable=False),
    sa.Column('changed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('changed_by_job_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_job_id'], ['scrape_jobs.id'], name=op.f('fk_change_history_changed_by_job_id_scrape_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], name=op.f('fk_change_history_changed_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_change_history'))
    )
    op.create_index('ix_change_history_entity', 'change_history', ['entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_table('company_projects',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=30), server_default='channel_partner', nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_company_projects_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_company_projects_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_projects')),
    sa.UniqueConstraint('company_id', 'project_id', 'role', name='uq_company_project_role')
    )
    op.create_table('emails',
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('email_type', sa.String(length=20), server_default='general', nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(company_id IS NOT NULL AND contact_id IS NULL) OR (company_id IS NULL AND contact_id IS NOT NULL)', name=op.f('ck_emails_owner_xor')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_emails_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_emails_contact_id_contacts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emails'))
    )
    op.create_index('ix_emails_company_id', 'emails', ['company_id'], unique=False)
    op.create_index('ix_emails_contact_id', 'emails', ['contact_id'], unique=False)
    op.create_index('ix_emails_email', 'emails', ['email'], unique=False)
    op.create_table('logs',
    sa.Column('scrape_job_id', sa.UUID(), nullable=True),
    sa.Column('level', sa.String(length=10), server_default='info', nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scrape_job_id'], ['scrape_jobs.id'], name=op.f('fk_logs_scrape_job_id_scrape_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_logs'))
    )
    op.create_index('ix_logs_level_created_at', 'logs', ['level', 'created_at'], unique=False)
    op.create_index('ix_logs_scrape_job_id', 'logs', ['scrape_job_id'], unique=False)
    op.create_table('merge_history',
    sa.Column('primary_company_id', sa.UUID(), nullable=False),
    sa.Column('duplicate_company_id', sa.UUID(), nullable=False),
    sa.Column('match_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('match_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('merged_by_user_id', sa.UUID(), nullable=True),
    sa.Column('merged_by_job_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['duplicate_company_id'], ['companies.id'], name=op.f('fk_merge_history_duplicate_company_id_companies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['merged_by_job_id'], ['scrape_jobs.id'], name=op.f('fk_merge_history_merged_by_job_id_scrape_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['merged_by_user_id'], ['users.id'], name=op.f('fk_merge_history_merged_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['primary_company_id'], ['companies.id'], name=op.f('fk_merge_history_primary_company_id_companies'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_merge_history')),
    sa.UniqueConstraint('duplicate_company_id', name=op.f('uq_merge_history_duplicate_company_id'))
    )
    op.create_index('ix_merge_history_primary_company_id', 'merge_history', ['primary_company_id'], unique=False)
    op.create_table('phone_numbers',
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('phone_number', sa.String(length=32), nullable=False),
    sa.Column('raw_value', sa.String(length=64), nullable=True),
    sa.Column('phone_type', sa.String(length=20), server_default='mobile', nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(company_id IS NOT NULL AND contact_id IS NULL) OR (company_id IS NULL AND contact_id IS NOT NULL)', name=op.f('ck_phone_numbers_owner_xor')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_phone_numbers_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_phone_numbers_contact_id_contacts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_phone_numbers'))
    )
    op.create_index('ix_phone_numbers_company_id', 'phone_numbers', ['company_id'], unique=False)
    op.create_index('ix_phone_numbers_contact_id', 'phone_numbers', ['contact_id'], unique=False)
    op.create_index('ix_phone_numbers_phone_number', 'phone_numbers', ['phone_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_phone_numbers_phone_number', table_name='phone_numbers')
    op.drop_index('ix_phone_numbers_contact_id', table_name='phone_numbers')
    op.drop_index('ix_phone_numbers_company_id', table_name='phone_numbers')
    op.drop_table('phone_numbers')
    op.drop_index('ix_merge_history_primary_company_id', table_name='merge_history')
    op.drop_table('merge_history')
    op.drop_index('ix_logs_scrape_job_id', table_name='logs')
    op.drop_index('ix_logs_level_created_at', table_name='logs')
    op.drop_table('logs')
    op.drop_index('ix_emails_email', table_name='emails')
    op.drop_index('ix_emails_contact_id', table_name='emails')
    op.drop_index('ix_emails_company_id', table_name='emails')
    op.drop_table('emails')
    op.drop_table('company_projects')
    op.drop_index('ix_change_history_entity', table_name='change_history')
    op.drop_table('change_history')
    op.drop_index('ix_websites_domain', table_name='websites')
    op.drop_table('websites')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_social_profiles_platform'), table_name='social_profiles')
    op.drop_table('social_profiles')
    op.drop_index('ix_service_areas_geom', table_name='service_areas', postgresql_using='gist')
    op.drop_index('ix_service_areas_company_id', table_name='service_areas')
    op.drop_index('ix_service_areas_city', table_name='service_areas')
    op.drop_table('service_areas')
    op.drop_index('ix_scrape_jobs_status_type', table_name='scrape_jobs')
    op.drop_index('ix_scrape_jobs_company_id', table_name='scrape_jobs')
    op.drop_table('scrape_jobs')
    op.drop_index('ix_rera_details_registrant_name_trgm', table_name='rera_details', postgresql_using='gin', postgresql_ops={'registrant_name': 'gin_trgm_ops'})
    op.drop_table('rera_details')
    op.drop_index('ix_projects_rera_number', table_name='projects')
    op.drop_index('ix_projects_geom', table_name='projects', postgresql_using='gist')
    op.drop_index('ix_projects_developer_id', table_name='projects')
    op.drop_index('ix_projects_city', table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_lead_scores_company_computed', table_name='lead_scores')
    op.drop_table('lead_scores')
    op.drop_index('ix_google_maps_listings_geom', table_name='google_maps_listings', postgresql_using='gist')
    op.drop_index('ix_google_maps_listings_company_id', table_name='google_maps_listings')
    op.drop_table('google_maps_listings')
    op.drop_index('ix_contacts_company_id', table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_company_specializations_specialization'), table_name='company_specializations')
    op.drop_table('company_specializations')
    op.drop_table('company_developer_partnerships')
    op.drop_table('company_categories')
    op.drop_index('ix_audit_logs_user_created', table_name='audit_logs')
    op.drop_index('ix_audit_logs_resource', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('uq_ai_summaries_company_current', table_name='ai_summaries', postgresql_where=sa.text('is_current'))
    op.drop_index('ix_ai_summaries_embedding', table_name='ai_summaries', postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('ai_summaries')
    op.drop_index('ix_addresses_geom', table_name='addresses', postgresql_using='gist')
    op.drop_index('ix_addresses_company_id', table_name='addresses')
    op.drop_index('ix_addresses_city', table_name='addresses')
    op.drop_table('addresses')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('developers')
    op.drop_index('ix_companies_status', table_name='companies')
    op.drop_index('ix_companies_name_trgm', table_name='companies', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index('ix_companies_last_crawled_at', table_name='companies')
    op.drop_table('companies')
    op.drop_table('business_categories')
    # ### end Alembic commands ###

    # Extensions are intentionally left installed on downgrade: dropping them
    # would CASCADE onto any other object created against them, which is unsafe
    # to assume away in a shared database. Drop manually if a full teardown is needed.
