"""add crawl snapshots

Revision ID: d3bd343165c9
Revises: a903c6999912
Create Date: 2026-07-19 17:57:39.204363
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3bd343165c9'
down_revision: Union[str, None] = 'a903c6999912'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_snapshots',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('scrape_job_id', sa.UUID(), nullable=True),
    sa.Column('website_id', sa.UUID(), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('page_type', sa.String(length=20), server_default='other', nullable=False),
    sa.Column('http_status', sa.SmallInteger(), nullable=True),
    sa.Column('raw_html_key', sa.String(length=500), nullable=True),
    sa.Column('clean_html_key', sa.String(length=500), nullable=True),
    sa.Column('markdown_key', sa.String(length=500), nullable=True),
    sa.Column('screenshot_key', sa.String(length=500), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('extracted_emails', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('extracted_phones', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('extracted_links', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('is_current', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('crawled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_crawl_snapshots_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scrape_job_id'], ['scrape_jobs.id'], name=op.f('fk_crawl_snapshots_scrape_job_id_scrape_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], name=op.f('fk_crawl_snapshots_website_id_websites'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crawl_snapshots'))
    )
    op.create_index('ix_crawl_snapshots_company_id', 'crawl_snapshots', ['company_id'], unique=False)
    op.create_index('ix_crawl_snapshots_content_hash', 'crawl_snapshots', ['content_hash'], unique=False)
    op.create_index('uq_crawl_snapshots_company_url_current', 'crawl_snapshots', ['company_id', 'url'], unique=True, postgresql_where=sa.text('is_current'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_crawl_snapshots_company_url_current', table_name='crawl_snapshots', postgresql_where=sa.text('is_current'))
    op.drop_index('ix_crawl_snapshots_content_hash', table_name='crawl_snapshots')
    op.drop_index('ix_crawl_snapshots_company_id', table_name='crawl_snapshots')
    op.drop_table('crawl_snapshots')
    # ### end Alembic commands ###
